spring:
  application:
    name: service-hi
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
server:
  port: 8762


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8762
#spring:
#  application:
#    name: service-hi
#  datasource:
#    url: jdbc:mysql://localhost:3306/dbgirl?characterEncoding=utf-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update






#    # 项目contextPath
#    server.context-path=/jpa
#    # 服务端口
#    server.port=8080
#    # session最大超时时间(分钟)，默认为30
#    server.session-timeout=60
#    # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
#    #server.address=192.168.1.66
#
#    # tomcat最大线程数，默认为200
#    server.tomcat.max-threads=100
#    # tomcat的URI编码
#    server.tomcat.uri-encoding=UTF-8
#
#    #注意中文乱码
#    spring.datasource.url=jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
#    spring.datasource.username=root
#    spring.datasource.password=123
#    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#    # Specify the DBMS
#    spring.jpa.database = MYSQL
#    # Show or not log for each sql query
#    spring.jpa.show-sql = true
#    # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
#    spring.jpa.hibernate.ddl-auto = update
#    # Hibernate 4 naming strategy fully qualified name. Not supported with Hibernate 5.
#    spring.jpa.hibernate.naming.strategy = org.hibernate.cfg.ImprovedNamingStrategy
#    # stripped before adding them to the entity manager)
#    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect